local P=game:GetService("Players")local RS=game:GetService("RunService")local UIS=game:GetService("UserInputService")local VIM=game:GetService("VirtualInputManager")local H=game:GetService("HttpService")local L=game:GetService("Lighting")local CG=game:GetService("CoreGui")local C=workspace.CurrentCamera local M=workspace:FindFirstChild("Map")or workspace local LP=P.LocalPlayer local MO=LP:GetMouse()for _,v in pairs(CG:GetChildren())do if v.Name=="YukiHub"then v:Destroy()end end
local W=loadstring(game:HttpGet("https://raw.githubusercontent.com/Footagesus/WindUI/main/dist/main.lua"))()
local WN=W:CreateWindow({Title="Yuki Hub v5.0",Folder="YukiHub",Icon="solar:home-2-bold-duotone",NewElements=true,HideSearchBar=false,Topbar={Height=44,ButtonsType="Default"}})
local function T(t,i)return WN:Tab({Title=t,Icon=i,IconColor=Color3.fromHex("#83889E"),Border=true})end
local TB={M=T("Main","solar:home-2-bold-duotone"),E=T("ESP","solar:eye-bold-duotone"),A=T("Aimbot","solar:target-bold-duotone"),V=T("Visuals","solar:palette-bold-duotone"),X=T("Misc","solar:settings-bold-duotone"),H=T("HUD","solar:chart-bold-duotone"),C=T("Credits","solar:info-circle-bold-duotone")}
local S={aOn=false,aF=90,pOn=false,pV=150,pG=196.2,pT=nil,pL=true,pLF=1,eB=false,eL=false,eLC=Color3.fromRGB(0,255,100),eLM="Single",eLO="Character",pE=false,gn=false,hk=false,pl=false,gt=false,wn=false,br=false,bL=1,fv=false,fvV=70,fvO=C.FieldOfView,fg=false,fgS=0,fgE=1000,sk=false,skB=50,skE=50,sp=false,spV=32,nc=false,sr=false,srB=1.05,fl=false,ch=false,chL=10,chW=2,st=false,stV=100,af=false,hu=false,huF=true,huP=true,huK=true}
local LO={L.Ambient,L.Brightness,L.ClockTime,L.FogEnd,L.GlobalShadows,L.OutdoorAmbient,L.ColorShift_Top,L.ColorShift_Bottom,L.FogStart,L.ExposureCompensation}
local function CF(f)local c,cd=nil,f or 1e9 for _,p in pairs(P:GetPlayers())do if p~=LP and p.Character and p.Character:FindFirstChild("HumanoidRootPart")and p.Character:FindFirstChild("Humanoid")and p.Character.Humanoid.Health>0 then local ps,on=C:WorldToViewportPoint(p.Character.HumanoidRootPart.Position)if on then local d=(Vector2.new(ps.X,ps.Y)-Vector2.new(MO.X,MO.Y)).Magnitude;if d<cd then cd=d;c=p end end end end;return c end
local function GP(t)return t and t.Character and t.Character:FindFirstChild("HumanoidRootPart")and t.Character.HumanoidRootPart.Position end
local function TI(p)local t=p.Team;if not t then return"O",Color3.fromRGB(255,255,255)end;local n=t.Name:lower()if n:find("maniac")or n:find("killer")then return"K",Color3.fromRGB(255,80,80)end;if n:find("survivor")then return"S",Color3.fromRGB(100,255,100)end;return"O",Color3.fromRGB(255,255,255)end
local function CT(t)for k in pairs(t)do t[k]=nil end end
local pP,pV2={},{}
local function GV(t)local p=GP(t);if not p then return Vector3.new()end;local pr=pP[t];pP[t]=p;if pr then local v=(p-pr)/0.1;pV2[t]=pV2[t]and(pV2[t]*0.7+v*0.3)or v end;return pV2[t]or Vector3.new()end
local function AN(o,t,v,g)local dx=t.X-o.X;local dz=t.Z-o.Z;local dy=t.Y-o.Y;local d=math.sqrt(dx*dx+dz*dz)if d<1 then return nil end;local v2=v*v;local gv=g or 196.2;local a=(gv*d*d)/(2*v2);local b=-d;local c=a+dy;local disc=b*b-4*a*c;if disc<0 then return nil end;local sd=math.sqrt(disc);local ang=math.atan((-b+sd)/(2*a));if ang<0 then ang=math.atan((-b-sd)/(2*a))end;if ang<0 then return nil end;return ang end
local function AP(o,t,v,g)local at=t;if S.pL then local e=(t-o).Magnitude/(v*0.707)if e>0 then local pr=GP(S.pT)+GV(S.pT)*e*S.pLF;if pr then at=pr end end end;local ang=AN(o,at,v,g);if not ang then return nil end;local dx=at.X-o.X;local dz=at.Z-o.Z;local d=math.sqrt(dx*dx+dz*dz);local ho=math.tan(ang)*d;return at+Vector3.new(0,ho,0)end
local eBD,eLD={},{}local pHl,pLb={},{}local gH,gL,hH,hL,pH,gH2,gL2,wL={},{},{},{},{},{},{},{}local cT=0;local cG,cH,cP,cGt,cW={},{},{},{},{}
local function SC()CT(cG);CT(cH);CT(cP);CT(cGt);CT(cW)for _,o in pairs(M:GetDescendants())do if not o:IsA("Model")and not o:IsA("BasePart")then continue end;local n=o.Name:lower()if o:IsA("Model")then if n:find("generator")then table.insert(cG,o)elseif n:find("hook")then table.insert(cH,o)elseif n:find("pallet")then table.insert(cP,o)elseif n:find("gate")or n:find("exit")then table.insert(cGt,o)end end;if o:IsA("BasePart")and n:find("window")then table.insert(cW,o)end end end
local chL2={}for i=1,4 do chL2[i]=Drawing.new("Line");chL2[i].Thickness=2;chL2[i].Color=Color3.fromRGB(0,255,100);chL2[i].Transparency=0.8;chL2[i].Visible=false end
local hG=nil;local function MKH()if hG and hG.sg and hG.sg.Parent then pcall(function()hG.sg:Destroy()end)end;local sg=Instance.new("ScreenGui");sg.Name="YukiHubHUD";sg.Parent=CG;local f=Instance.new("Frame");f.Size=UDim2.new(0,180,0,80);f.Position=UDim2.new(1,-190,0,10);f.BackgroundColor3=Color3.fromRGB(15,15,25);f.BackgroundTransparency=0.3;f.BorderSizePixel=0;f.Parent=sg;Instance.new("UICorner",f).CornerRadius=UDim.new(0,6);local st=Instance.new("UIStroke",f);st.Color=Color3.fromRGB(50,50,70);st.Thickness=1;local ly=Instance.new("UIListLayout",f);ly.Padding=UDim.new(0,2);local pd=Instance.new("UIPadding",f);pd.PaddingTop=UDim.new(0,6);pd.PaddingLeft=UDim.new(0,8);pd.PaddingBottom=UDim.new(0,6);local function Lb(c)local l=Instance.new("TextLabel",f);l.Size=UDim2.new(1,0,0,18);l.BackgroundTransparency=1;l.TextColor3=c;l.Font=Enum.Font.SourceSansSemibold;l.TextSize=15;l.TextXAlignment=Enum.TextXAlignment.Left;return l end;hG={sg=sg,frame=f,fps=Lb(Color3.fromRGB(100,255,100)),ping=Lb(Color3.fromRGB(100,200,255)),killer=Lb(Color3.fromRGB(255,100,100))};hG.fps.Text="FPS: 0";hG.ping.Text="Ping: 0ms";hG.killer.Text="Killer: --"end
TB.M:Toggle({Title="Walkspeed",Callback=function(s)if LP.Character and LP.Character:FindFirstChild("Humanoid")then LP.Character.Humanoid.WalkSpeed=s and 50 or 16 end end})
TB.M:Space()TB.M:Slider({Title="Walkspeed Value",Width=200,Value={Min=16,Max=250,Default=50},Step=1,Callback=function(v)if LP.Character and LP.Character:FindFirstChild("Humanoid")then LP.Character.Humanoid.WalkSpeed=v end end})
TB.M:Space()TB.M:Dropdown({Title="Jump Power",Values={"50","75","100","150","200"},Value=1,Callback=function(s)if LP.Character and LP.Character:FindFirstChild("Humanoid")then LP.Character.Humanoid.JumpPower=tonumber(s)end end})
TB.M:Space()TB.M:Button({Title="Rejoin",Callback=function()game:GetService("TeleportService"):Teleport(game.PlaceId,LP)end})
TB.M:Space()TB.M:Button({Title="Server Hop",Callback=function()local function gs(c)local u="https://games.roblox.com/v1/games/"..game.PlaceId.."/servers/Public?limit=100";if c then u=u.."&cursor="..c end;return H:JSONDecode(game:HttpGet(u))end;local s=gs()if s and s.data then for _,v in pairs(s.data)do if v.playing<v.maxPlayers and v.id~=game.JobId then game:GetService("TeleportService"):TeleportToPlaceInstance(game.PlaceId,v.id,LP);return end end end end})
TB.E:Toggle({Title="Player ESP",Desc="Highlight + name + distance + status",Callback=function(s)S.pE=s;if not s then for _,v in pairs(pHl)do pcall(function()v:Destroy()end)end;CT(pHl);for _,v in pairs(pLb)do pcall(function()v.Parent:Destroy()end)end;CT(pLb)end end})
TB.E:Space()TB.E:Toggle({Title="ESP Box",Callback=function(s)S.eB=s;if s then for _,p in pairs(P:GetPlayers())do if p~=LP then local bx=Drawing.new("Square");bx.Thickness=2;bx.Color=Color3.fromRGB(255,50,50);bx.Filled=false;bx.Visible=false;local nl=Drawing.new("Text");nl.Center=true;nl.Size=14;nl.Outline=true;nl.Color=Color3.fromRGB(255,255,255);nl.Visible=false;eBD[p]={Box=bx,Name=nl}end end else for _,o in pairs(eBD)do o.Box.Visible=false;o.Name.Visible=false end end end})
TB.E:Space()TB.E:Toggle({Title="ESP Line",Callback=function(s)S.eL=s;if not s then for _,o in pairs(eLD)do o.Visible=false end end end})
TB.E:Space()TB.E:Colorpicker({Title="Line Color",Default=S.eLC,Callback=function(c)S.eLC=c end})
TB.E:Space()TB.E:Dropdown({Title="Line Mode",Values={"Single","All Players"},Value=1,Callback=function(s)S.eLM=(s=="All Players")and"All"or"Single"end})
TB.E:Space()TB.E:Dropdown({Title="Line Origin",Values={"Character","Top Screen"},Value=1,Callback=function(s)S.eLO=s end})
TB.E:Space()TB.E:Toggle({Title="Projectile Arc",Desc="Trajectory prediction",Callback=function(s)if not s and S.pA then S.pA.Visible=false end end})
TB.E:Space()TB.E:Toggle({Title="Generator ESP",Callback=function(s)S.gn=s;if not s then for _,v in pairs(gH)do pcall(function()v:Destroy()end)end;CT(gH);for _,v in pairs(gL)do pcall(function()v.Parent:Destroy()end)end;CT(gL)end end})
TB.E:Space()TB.E:Toggle({Title="Hook ESP",Callback=function(s)S.hk=s;if not s then for _,v in pairs(hH)do pcall(function()v:Destroy()end)end;CT(hH);for _,v in pairs(hL)do pcall(function()v.Parent:Destroy()end)end;CT(hL)end end})
TB.E:Space()TB.E:Toggle({Title="Pallet ESP",Callback=function(s)S.pl=s;if not s then for _,v in pairs(pH)do pcall(function()v:Destroy()end)end;CT(pH)end end})
TB.E:Space()TB.E:Toggle({Title="Gate ESP",Callback=function(s)S.gt=s;if not s then for _,v in pairs(gH2)do pcall(function()v:Destroy()end)end;CT(gH2);for _,v in pairs(gL2)do pcall(function()v.Parent:Destroy()end)end;CT(gL2)end end})
TB.E:Space()TB.E:Toggle({Title="Window ESP",Callback=function(s)S.wn=s;if not s then for _,v in pairs(wL)do pcall(function()v.Parent:Destroy()end)end;CT(wL)end end})
TB.A:Toggle({Title="Basic Aimbot",Callback=function(s)S.aOn=s end})
TB.A:Space()TB.A:Slider({Title="Smoothness",Width=200,Value={Min=1,Max=10,Default=1},Step=1,Callback=function(v)S.aS=v end})
TB.A:Space()TB.A:Slider({Title="FOV",Width=200,Value={Min=10,Max=360,Default=90},Step=1,Callback=function(v)S.aF=v end})
TB.A:Space()TB.A:Toggle({Title="Projectile Aimbot",Desc="For arcing weapons",Callback=function(s)S.pOn=s end})
TB.A:Space()TB.A:Slider({Title="Proj. Velocity",Width=200,Value={Min=30,Max=500,Default=150},Step=5,Callback=function(v)S.pV=v end})
TB.A:Space()TB.A:Slider({Title="Gravity",Width=200,Value={Min=50,Max=500,Default=196.2},Step=1,Callback=function(v)S.pG=v end})
TB.A:Space()TB.A:Toggle({Title="Lead Prediction",Callback=function(s)S.pL=s end})
TB.A:Space()TB.A:Slider({Title="Lead Factor",Width=200,Value={Min=0.5,Max=3,Default=1},Step=0.1,Callback=function(v)S.pLF=v end})
TB.A:Space()TB.A:Button({Title="Lock Target",Color=Color3.fromRGB(0,120,255),Callback=function()S.pT=CF(360)end})
TB.A:Space()TB.A:Button({Title="Unlock Target",Color=Color3.fromRGB(255,50,50),Callback=function()S.pT=nil end})
TB.V:Toggle({Title="Bright Mode",Desc="Full bright",Callback=function(s)S.br=s;if s then LO[1],LO[2],LO[3],LO[4],LO[5],LO[6],LO[7],LO[8]=L.Ambient,L.Brightness,L.ClockTime,L.FogEnd,L.GlobalShadows,L.OutdoorAmbient,L.ColorShift_Top,L.ColorShift_Bottom else L.Ambient=LO[1];L.Brightness=LO[2];L.ClockTime=LO[3];L.FogEnd=LO[4];L.GlobalShadows=LO[5];L.OutdoorAmbient=LO[6];L.ColorShift_Top=LO[7];L.ColorShift_Bottom=LO[8]end end})
TB.V:Space()TB.V:Slider({Title="Bright Level",Width=200,Value={Min=0.5,Max=5,Default=1},Step=0.1,Callback=function(v)S.bL=v end})
TB.V:Space()TB.V:Toggle({Title="Custom FOV",Callback=function(s)S.fv=s;C.FieldOfView=s and S.fvV or S.fvO end})
TB.V:Space()TB.V:Slider({Title="FOV Value",Width=200,Value={Min=30,Max=120,Default=70},Step=1,Callback=function(v)S.fvV=v;if S.fv then C.FieldOfView=v end end})
TB.V:Space()TB.V:Toggle({Title="Custom Fog",Callback=function(s)S.fg=s;if not s then L.FogStart=LO[9];L.FogEnd=LO[4]end end})
TB.V:Space()TB.V:Slider({Title="Fog Start",Width=200,Value={Min=0,Max=500,Default=0},Step=1,Callback=function(v)S.fgS=v end})
TB.V:Space()TB.V:Slider({Title="Fog End",Width=200,Value={Min=100,Max=2000,Default=1000},Step=10,Callback=function(v)S.fgE=v end})
TB.V:Space()TB.V:Toggle({Title="Skybox",Callback=function(s)S.sk=s;if not s then L.Brightness=LO[2];L.ExposureCompensation=LO[10]end end})
TB.V:Space()TB.V:Slider({Title="Sky Brightness",Width=200,Value={Min=0,Max=100,Default=50},Step=1,Callback=function(v)S.skB=v end})
TB.V:Space()TB.V:Slider({Title="Exposure",Width=200,Value={Min=0,Max=100,Default=50},Step=1,Callback=function(v)S.skE=v end})
TB.X:Toggle({Title="Speedhack",Callback=function(s)S.sp=s end})
TB.X:Space()TB.X:Slider({Title="Speed Value",Width=200,Value={Min=16,Max=100,Default=32},Step=1,Callback=function(v)S.spV=v end})
TB.X:Space()TB.X:Toggle({Title="Sprint",Desc="Hold Shift",Callback=function(s)S.sr=s end})
TB.X:Space()TB.X:Slider({Title="Sprint Boost",Width=200,Value={Min=1.0,Max=2.0,Default=1.05},Step=0.05,Callback=function(v)S.srB=v end})
TB.X:Space()TB.X:Toggle({Title="Noclip",Callback=function(s)S.nc=s end})
TB.X:Space()TB.X:Toggle({Title="Custom Crosshair",Callback=function(s)S.ch=s end})
TB.X:Space()TB.X:Slider({Title="CH Length",Width=200,Value={Min=5,Max=30,Default=10},Step=1,Callback=function(v)S.chL=v end})
TB.X:Space()TB.X:Slider({Title="CH Width",Width=200,Value={Min=1,Max=8,Default=2},Step=1,Callback=function(v)S.chW=v end})
TB.X:Space()TB.X:Toggle({Title="Flashlight",Callback=function(s)S.fl=s end})
TB.X:Space()TB.X:Toggle({Title="Stretched Res",Callback=function(s)S.st=s end})
TB.X:Space()TB.X:Slider({Title="Stretch Amount",Width=200,Value={Min=50,Max=200,Default=100},Step=5,Callback=function(v)S.stV=v end})
TB.X:Space()TB.X:Button({Title="Reset Character",Callback=function()if LP.Character and LP.Character:FindFirstChild("Humanoid")then LP.Character.Humanoid.Health=0 end end})
TB.X:Space()TB.X:Button({Title="Anti AFK",Callback=function()if S.af then return end;S.af=true;LP.Idled:Connect(function()VIM:SendMouseButtonEvent(0,0,0,true,game,1);task.wait(0.1);VIM:SendMouseButtonEvent(0,0,0,false,game,1)end)end})
TB.X:Space()TB.X:Slider({Title="FPS Cap",Width=200,Value={Min=15,Max=360,Default=60},Step=1,Callback=function(v)setfpscap(v)end})
TB.X:Space()TB.X:Button({Title="Infinite Yield",Callback=function()loadstring(game:HttpGet("https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source"))()end})
TB.H:Toggle({Title="Enable HUD",Desc="FPS, Ping, Killer",Callback=function(s)S.hu=s end})
TB.H:Space()TB.H:Toggle({Title="Show FPS",Default=true,Callback=function(s)S.huF=s end})
TB.H:Space()TB.H:Toggle({Title="Show Ping",Default=true,Callback=function(s)S.huP=s end})
TB.H:Space()TB.H:Toggle({Title="Show Killer",Default=true,Callback=function(s)S.huK=s end})
TB.C:Button({Title="Yuki Hub v5.0",Desc="Made for Tuan | WindUI",Callback=function()end})
TB.C:Space()TB.C:Button({Title="Features:",Desc="ESP, Aimbot, Visuals, Misc, HUD",Callback=function()end})
TB.C:Space()TB.C:Button({Title="Merged from:",Desc="Essential Script + Notties Script",Callback=function()end})
local hF,hTm,hFps=0,0,0;local fO=nil
RS:RenderStepped:Connect(function(dt)
if S.br then L.Ambient=Color3.fromRGB(255,255,255);L.Brightness=S.bL*2;L.ClockTime=12;L.FogEnd=100000;L.GlobalShadows=false;L.OutdoorAmbient=Color3.fromRGB(255,255,255);L.ColorShift_Top=Color3.fromRGB(255,255,255);L.ColorShift_Bottom=Color3.fromRGB(255,255,255)end
if S.fv then C.FieldOfView=S.fvV end
if S.fg then L.FogStart=S.fgS;L.FogEnd=S.fgE end
if S.sk and not S.br then L.Brightness=S.skB/10;L.ExposureCompensation=S.skE/10 end
if S.sp and LP.Character and LP.Character:FindFirstChild("Humanoid")then LP.Character.Humanoid.WalkSpeed=S.spV end
if S.nc and LP.Character then for _,p in pairs(LP.Character:GetDescendants())do if p:IsA("BasePart")then p.CanCollide=false end end end
if S.sr and LP.Character and LP.Character:FindFirstChild("Humanoid")then local sh=UIS:IsKeyDown(Enum.KeyCode.LeftShift)or UIS:IsKeyDown(Enum.KeyCode.RightShift);LP.Character.Humanoid.WalkSpeed=sh and(16*S.srB)or 16 end
if S.ch then local cx=C.ViewportSize.X/2;local cy=C.ViewportSize.Y/2;local l=S.chL;local w=S.chW;for i=1,4 do chL2[i].Visible=true;chL2[i].Thickness=w end;chL2[1].From=Vector2.new(cx,cy-l);chL2[1].To=Vector2.new(cx,cy-2);chL2[2].From=Vector2.new(cx,cy+2);chL2[2].To=Vector2.new(cx,cy+l);chL2[3].From=Vector2.new(cx-l,cy);chL2[3].To=Vector2.new(cx-2,cy);chL2[4].From=Vector2.new(cx+2,cy);chL2[4].To=Vector2.new(cx+l,cy)else for i=1,4 do chL2[i].Visible=false end end
if S.st then C.ViewportSize=Vector2.new(C.ViewportSize.X*(S.stV/100),C.ViewportSize.Y)end
if S.eB then for plr,o in pairs(eBD)do if plr.Character and plr.Character:FindFirstChild("HumanoidRootPart")then local rt=plr.Character.HumanoidRootPart;local ps,on=C:WorldToViewportPoint(rt.Position)if on then local sz=Vector2.new(2000/ps.Z,3000/ps.Z);o.Box.Size=sz;o.Box.Position=Vector2.new(ps.X-sz.X/2,ps.Y-sz.Y/2);o.Box.Visible=true;o.Name.Position=Vector2.new(ps.X,ps.Y-sz.Y/2-16);o.Name.Text=plr.Name;o.Name.Visible=true else o.Box.Visible=false;o.Name.Visible=false end else o.Box.Visible=false;o.Name.Visible=false end end end
if S.eL then local mp,msp=nil,nil;if LP.Character and LP.Character:FindFirstChild("HumanoidRootPart")then mp=LP.Character.HumanoidRootPart.Position;msp,_=C:WorldToViewportPoint(mp)end;local ori;if S.eLO=="Top Screen"then ori=Vector2.new(C.ViewportSize.X/2,0)elseif msp then ori=Vector2.new(msp.X,msp.Y)else for _,o in pairs(eLD)do o.Visible=false end;return end;local tg={};if S.eLM=="Single"then local t=S.pT or CF(360);if t then table.insert(tg,t)end else for _,p in pairs(P:GetPlayers())do if p~=LP and p.Character and p.Character:FindFirstChild("HumanoidRootPart")and p.Character:FindFirstChild("Humanoid")and p.Character.Humanoid.Health>0 then table.insert(tg,p)end end end;for i=#tg+1,#eLD do eLD[i].Visible=false end;for i,t in ipairs(tg)do if not eLD[i]then eLD[i]=Drawing.new("Line");eLD[i].Thickness=2;eLD[i].Color=S.eLC;eLD[i].Transparency=0.6 end;local tp=t.Character and t.Character:FindFirstChild("HumanoidRootPart")and t.Character.HumanoidRootPart.Position;if tp then local to,_=C:WorldToViewportPoint(tp);eLD[i].From=ori;eLD[i].To=Vector2.new(to.X,to.Y);eLD[i].Visible=true;eLD[i].Color=S.eLC else eLD[i].Visible=false end end end
if S.pT and LP.Character and LP.Character:FindFirstChild("HumanoidRootPart")then local tp=GP(S.pT)if tp then local og=LP.Character.HumanoidRootPart.Position;local tr=tp;local vl=S.pV;local gv=S.pG;if not S.pA then S.pA=Drawing.new("Line");S.pA.Thickness=1;S.pA.Color=Color3.fromRGB(255,200,50);S.pA.Transparency=0.3 end;local ang=AN(og,tr,vl,gv)if ang then local dx=tr.X-og.X;local dz=tr.Z-og.Z;local di=Vector2.new(dx,dz).Unit;local g=gv;local v=vl;local vx=v*math.cos(ang);local vy=v*math.sin(ang);local pts={};local tt=(2*vy)/g;for t=0,tt,0.1 do local x=vx*t;local y=vy*t-0.5*g*t*t;local pos=og+Vector3.new(di.X*x,y,di.Y*x);local sp,_=C:WorldToViewportPoint(pos);table.insert(pts,Vector2.new(sp.X,sp.Y))end;if #pts>1 then S.pA.Visible=true;S.pA.Points=pts else S.pA.Visible=false end else S.pA.Visible=false end end end
if S.aOn and LP.Character and LP.Character:FindFirstChild("HumanoidRootPart")then local c=CF(S.aF)if c and c.Character then local ps=C:WorldToViewportPoint(c.Character.HumanoidRootPart.Position);local t=Vector2.new(ps.X,ps.Y);local cr=Vector2.new(MO.X,MO.Y);local s=t:Lerp(cr,1/(S.aS or 1));mousemoverel(s.X-cr.X,s.Y-cr.Y)end end
if S.pOn and LP.Character and LP.Character:FindFirstChild("HumanoidRootPart")then local tg=S.pT or CF(360)if tg and tg.Character and tg.Character:FindFirstChild("HumanoidRootPart")and tg.Character:FindFirstChild("Humanoid")and tg.Character.Humanoid.Health>0 then local og=LP.Character.HumanoidRootPart.Position;local tP=tg.Character.HumanoidRootPart.Position;local am=AP(og,tP,S.pV,S.pG)if am then local ps,on=C:WorldToViewportPoint(am);if on then local t=Vector2.new(ps.X,ps.Y);local cr=Vector2.new(MO.X,MO.Y);local s=t:Lerp(cr,1/(S.aS or 1));mousemoverel(s.X-cr.X,s.Y-cr.Y)end end end end
if S.pE then for _,plr in pairs(P:GetPlayers())do if plr==LP then continue end;local ch=plr.Character;if not ch then continue end;local hd=ch:FindFirstChild("Head")or ch:FindFirstChild("HumanoidRootPart");if not hd then continue end;local tt,bc=TI(plr);local hm=ch:FindFirstChildOfClass("Humanoid")or ch:FindFirstChild("Humanoid");local hk=ch:GetAttribute("IsHooked")or ch:GetAttribute("Hooked");local kn=hm and hm.Health<hm.MaxHealth*0.3;local cl=bc;if tt=="S"then if hk then cl=Color3.fromRGB(255,110,80);elseif kn then cl=Color3.fromRGB(255,170,80);elseif hm and hm.Health<hm.MaxHealth then cl=Color3.fromRGB(255,255,120);else cl=Color3.fromRGB(100,255,100)end end;if not pHl[plr]then local hl=Instance.new("Highlight");hl.DepthMode=Enum.HighlightDepthMode.AlwaysOnTop;hl.OutlineColor=Color3.new(1,1,1);hl.FillTransparency=0.5;hl.Parent=C;pHl[plr]=hl end;local hl=pHl[plr];hl.Adornee=ch;hl.FillColor=cl;hl.FillTransparency=0.3;hl.OutlineTransparency=0;if not pLb[plr]or not pLb[plr].Parent then local bl=Instance.new("BillboardGui");bl.Size=UDim2.new(0,200,0,50);bl.StudsOffset=Vector3.new(0,3,0);bl.AlwaysOnTop=true;bl.Parent=C;local tx=Instance.new("TextLabel");tx.Size=UDim2.new(1,0,1,0);tx.BackgroundTransparency=1;tx.Font=Enum.Font.SourceSansSemibold;tx.TextSize=14;tx.TextStrokeTransparency=0.3;tx.TextStrokeColor3=Color3.new(0,0,0);tx.TextXAlignment=Enum.TextXAlignment.Center;tx.Parent=bl;pLb[plr]=tx end;local tx=pLb[plr];tx.Parent.Adornee=hd;local ds=0;if LP.Character and LP.Character:FindFirstChild("HumanoidRootPart")then ds=math.floor((hd.Position-LP.Character.HumanoidRootPart.Position).Magnitude)end;local l3=tostring(ds).."m";local l2="";if tt=="K"then local sk=plr:GetAttribute("SelectedKiller")or plr:GetAttribute("KillerName");l2=sk and"KILLER: "..tostring(sk)or"KILLER"elseif tt=="S"then if hk then l2="HOOKED";elseif kn then l2="HURT"end end;tx.Text=plr.Name.." | "..l3..(l2~=""and(" | "..l2)or"");tx.TextColor3=cl end end
cT=cT+dt;if cT>=2 then cT=0;SC()end
if S.gn then for _,o in pairs(cG)do local at=o.PrimaryPart or o:FindFirstChildWhichIsA("BasePart");if not at then continue end;if not gH[o]then local hl=Instance.new("Highlight");hl.DepthMode=Enum.HighlightDepthMode.AlwaysOnTop;hl.FillTransparency=0.5;hl.OutlineTransparency=0;hl.FillColor=Color3.new(1,1,1);hl.OutlineColor=Color3.new(1,1,1);hl.Parent=C;gH[o]=hl;local bl=Instance.new("BillboardGui");bl.Size=UDim2.new(0,150,0,30);bl.StudsOffset=Vector3.new(0,2.5,0);bl.AlwaysOnTop=true;bl.Parent=C;local tx=Instance.new("TextLabel");tx.Size=UDim2.new(1,0,1,0);tx.BackgroundTransparency=1;tx.Font=Enum.Font.SourceSansSemibold;tx.TextSize=14;tx.TextStrokeTransparency=0.4;tx.TextStrokeColor3=Color3.new(0,0,0);tx.TextXAlignment=Enum.TextXAlignment.Center;tx.TextColor3=Color3.fromRGB(200,200,255);tx.Text="Generator";tx.Parent=bl;gL[o]=tx end;gH[o].Adornee=o;gL[o].Parent.Adornee=at end end
if S.hk then for _,o in pairs(cH)do local at=o.PrimaryPart or o:FindFirstChildWhichIsA("BasePart");if not at then continue end;if not hH[o]then local hl=Instance.new("Highlight");hl.DepthMode=Enum.HighlightDepthMode.AlwaysOnTop;hl.FillTransparency=0.6;hl.FillColor=Color3.fromRGB(255,80,80);hl.OutlineColor=Color3.fromRGB(255,0,0);hl.Parent=C;hH[o]=hl;local bl=Instance.new("BillboardGui");bl.Size=UDim2.new(0,100,0,30);bl.StudsOffset=Vector3.new(0,2,0);bl.AlwaysOnTop=true;bl.Parent=C;local tx=Instance.new("TextLabel");tx.Size=UDim2.new(1,0,1,0);tx.BackgroundTransparency=1;tx.Font=Enum.Font.SourceSansSemibold;tx.TextSize=14;tx.TextStrokeTransparency=0.4;tx.TextStrokeColor3=Color3.new(0,0,0);tx.TextXAlignment=Enum.TextXAlignment.Center;tx.TextColor3=Color3.fromRGB(255,100,100);tx.Text="Hook";tx.Parent=bl;hL[o]=tx end;hH[o].Adornee=o end end
if S.pl then for _,o in pairs(cP)do local at=o.PrimaryPart or o:FindFirstChildWhichIsA("BasePart");if not at then continue end;if not pH[o]then local hl=Instance.new("Highlight");hl.DepthMode=Enum.HighlightDepthMode.AlwaysOnTop;hl.FillTransparency=0.5;hl.OutlineTransparency=0;hl.FillColor=Color3.fromRGB(255,255,100);hl.OutlineColor=Color3.fromRGB(255,200,0);hl.Parent=C;pH[o]=hl end;pH[o].Adornee=o end end
if S.gt then for _,o in pairs(cGt)do local at=o.PrimaryPart or o:FindFirstChildWhichIsA("BasePart");if not at then continue end;if not gH2[o]then local hl=Instance.new("Highlight");hl.DepthMode=Enum.HighlightDepthMode.AlwaysOnTop;hl.FillTransparency=0.5;hl.OutlineTransparency=0;hl.FillColor=Color3.fromRGB(160,0,255);hl.OutlineColor=Color3.fromRGB(200,120,255);hl.Parent=C;gH2[o]=hl;local bl=Instance.new("BillboardGui");bl.Size=UDim2.new(0,100,0,30);bl.StudsOffset=Vector3.new(0,2,0);bl.AlwaysOnTop=true;bl.Parent=C;local tx=Instance.new("TextLabel");tx.Size=UDim2.new(1,0,1,0);tx.BackgroundTransparency=1;tx.Font=Enum.Font.SourceSansSemibold;tx.TextSize=14;tx.TextStrokeTransparency=0.4;tx.TextStrokeColor3=Color3.new(0,0,0);tx.TextXAlignment=Enum.TextXAlignment.Center;tx.TextColor3=Color3.fromRGB(200,150,255);tx.Text="Gate";tx.Parent=bl;gL2[o]=tx end;gH2[o].Adornee=at end end
if S.wn then for _,o in pairs(cW)do if not wL[o]then local bl=Instance.new("BillboardGui");bl.Size=UDim2.new(0,80,0,25);bl.StudsOffset=Vector3.new(0,1.5,0);bl.AlwaysOnTop=true;bl.Parent=C;local tx=Instance.new("TextLabel");tx.Size=UDim2.new(1,0,1,0);tx.BackgroundTransparency=1;tx.Font=Enum.Font.SourceSansSemibold;tx.TextSize=12;tx.TextStrokeTransparency=0.4;tx.TextStrokeColor3=Color3.new(0,0,0);tx.TextXAlignment=Enum.TextXAlignment.Center;tx.TextColor3=Color3.fromRGB(180,230,255);tx.Text="Window";tx.Parent=bl;wL[o]=tx end;wL[o].Parent.Adornee=o end end
if S.hu then if not hG then MKH()end;hF=hF+1;hTm=hTm+dt;if hTm>=1 then hFps=math.floor(hF/hTm);hF=0;hTm=0 end;if S.huF then hG.fps.Text="FPS: "..tostring(hFps);hG.fps.Visible=true else hG.fps.Visible=false end;if S.huP then local pn=math.floor(LP:GetNetworkPing()*1000);hG.ping.Text="Ping: "..tostring(pn).."ms";hG.ping.Visible=true else hG.ping.Visible=false end;if S.huK then local kn="--";for _,plr in pairs(P:GetPlayers())do if plr~=LP and plr.Character and plr.Character:FindFirstChild("Humanoid")and plr.Character.Humanoid.Health>0 then local tm=plr.Team;if tm and(tm.Name:lower():find("maniac")or tm.Name:lower():find("killer"))then kn=plr.Name;break end end end;hG.killer.Text="Killer: "..kn;hG.killer.Visible=true else hG.killer.Visible=false end;local vc=0;if hG.fps.Visible then vc=vc+1 end;if hG.ping.Visible then vc=vc+1 end;if hG.killer.Visible then vc=vc+1 end;hG.frame.Size=UDim2.new(0,180,0,8+vc*22)elseif hG then pcall(function()hG.sg:Destroy()end);hG=nil end end)
RS:Heartbeat:Connect(function()if S.fl then if not fO then fO=Instance.new("SpotLight");fO.Brightness=2;fO.Range=60;fO.Angle=90;fO.Face=Enum.NormalId.Front;fO.Parent=C end;fO.Enabled=true elseif fO then fO.Enabled=false end end)